import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h1>logo</h1>
          <ul>
            <li>
              <a href="/about">About</a>
            </li>
            <li>
              <a href='/'>home</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
